[features]
seeds = false
skip-lint = false
[programs.devnet]
contacts = "7oGTeV9zzmmL4GbBLWC6AUt29WjBdRhj1f3jZeuvAmwe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
